import { Navbar } from '@/components/Navbar' // <---Forma de next js llamado el import alias-->
// import { Navbar } from '../components/Navbar'
import { Roboto } from 'next/font/google'
import './styles.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
})

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
